#Training
max_episodes: 10000000
print_freq: 100 # print avg reward in the interval (in episodes)

#PPO
batch_size: 512
actor_lr: 0.0003
critic_lr: 0.0003
gamma: 0.99
epochs_per_batch: 6
eps_clip: 0.1
lmbda: 0.95

#Architecture - Actor
actor_n_blocks: 6
actor_n_blocks_after_split: 2
actor_intermediate_channels: 32

#Architecture - Critic
critic_n_blocks: 6
critic_intermediate_channels: 16

#Other 
device: cuda #cuda, cpu, mps
path:  None #model.t 
save_path: model.t
video_save_rate: 1000 #How often to save a video, in episodes

#Reward
unit_lost_scale: 0.1
units_killed_scale: 1
factory_lost_scale: 10

lichen_divide_value: 20000
scaling_lichen: 5
scaling_ice: 0.1 #Value of ice
scaling_ore: 0.05
scaling_delivery_extra: 2 #How much more delivery is worth compared to gathering
scaling_win: 5
