#Training
max_episodes: 50000000

#PPO
num_steps_per_env: 32
num_minibatches: 4
lr: 0.00025
gamma: 0.97
epochs_per_batch: 4
eps_clip: 0.2
lmbda: 0.95
ent_coef: 0.001
vf_coef: 0.5
max_grad_norm: 0.5
use_target_kl: True
target_kl_max: 0.3
target_kl_min : 0
anneal_lr: False
norm_adv: True
clip_loss_value: False #According to 37 PPO implementation details, this should be false
mode_or_sample: sample #sample

#Parallelization
parallel_envs: 16


#Environment
map_size: 32
n_factories: 2
max_game_length: 2000

#Architecture - Actor
actor_n_blocks: 16
actor_intermediate_channels: 32
actor_use_batch_norm: False

#Architecture - Teacher
teacher_actor_n_blocks: 4
teacher_actor_intermediate_channels: 64
teacher_actor_use_batch_norm: False

#Teacher stuff:
KL_factor: 0
KL_steps_to_anneal: 5000000
teacher_path: smaller_model_checkpoint.t

#Other 
device: cuda #cuda, cpu, mps
path: None #most_recent.t
save_path: bigger_model.t #model.t
log_to_wb: True
log_rate: 20000 #Log every 100k steps ish


#Reward
unit_punishment: 0 #0.05
rubble_reward: 0.005
scaling_ice: 0.025 #Value of ice
scaling_ore: 0.0005
scaling_water: 0.05
scaling_metal: 0.025

factory_lost: 0 #0.5
scaling_win: 0
