#Training
max_episodes: 10000000000000
print_freq: 100 # print avg reward in the interval (in episodes)

#PPO
num_steps_per_env: 64
num_minibatches: 8
lr: 0.00025
gamma: 1
epochs_per_batch: 2
eps_clip: 0.2
lmbda: 0.95
ent_coef: 0.001
vf_coef: 0.5
max_grad_norm: 0.5
use_target_kl: True
target_kl_max: 0.03
target_kl_min : 0.001
anneal_lr: True
norm_adv: True
clip_loss_value: False #According to 37 PPO implementation details, this should be false
mode_or_sample: sample #sample

#Environment
map_size: 48
n_factories: 4

#Architecture - Actor
actor_n_blocks: 20
actor_n_blocks_after_split: 2
actor_intermediate_channels: 32

#Architecture - Critic
critic_n_blocks: 8
critic_intermediate_channels: 16

#Other 
device: cuda #cuda, cpu, mps
path: None #model.t
save_path: bigger_model.t #model.t
video_save_rate: 1000 #How often to save a video, in episodes
log_to_wb: True
log_rate: 100000 #Log every 100k steps ish

#Parallelization
parallel_envs: 16

#Reward
heavy_unit_reward: 0 #0.05

lichen_divide_value: 20000
scaling_lichen: 5
scaling_ice: 0.005 #Value of ice
scaling_ore: 0.005 #0.005
scaling_water_made: 0.01
scaling_metal_made: 0.01
scaling_win: 0
