#Training
max_episodes: 1000000

#PPO
num_steps_per_env: 64
num_minibatches: 8
lr: 0.003
epochs_per_batch: 4
anneal_lr: True
mode_or_sample: sample #sample

#Parallelization
parallel_envs: 16


#Environment
map_size: 48
n_factories: 2
max_game_length: 2000

#Architecture - Actor
actor_n_blocks: 4
actor_intermediate_channels: 32
actor_use_batch_norm: False

#Architecture - Actor
student_actor_n_blocks: 12
student_actor_intermediate_channels: 32
student_actor_use_batch_norm: False

#Other 
device: cuda #cuda, cpu, mps
path: bigger_model.t #model.t
student_save_path: student_model.t #model.t
log_to_wb: True
log_rate: 5000   #Log every 100k steps ish

